om sri achyutha anantha govinda
om sri achyutha anantha govinda
om sri achyutha anantha govinda
om sri achyutha anantha govinda
om sri achyutha anantha govinda
om sri achyutha anantha govinda
om sri achyutha anantha govinda
om sri achyutha anantha govinda
om sri achyutha anantha govinda
om sri achyutha anantha govinda
om sri achyutha anantha govinda
om sri achyutha anantha govinda
om sri achyutha anantha govinda
om sri achyutha anantha govinda
om sri achyutha anantha govinda
om sri achyutha anantha govinda 
om sri achyutha anantha govinda
om sri achyutha anantha govinda
om sri achyutha anantha govinda
om sri achyutha anantha govinda
om sri achyutha anantha govinda
om sri achyutha anantha govinda
om sri achyutha anantha govinda
om sri achyutha anantha govinda
om sri achyutha anantha govinda
om sri achyutha anantha govinda
om sri achyutha anantha govinda
om sri achyutha anantha govinda
om sri achyutha anantha govinda
om sri achyutha anantha govinda
pm sri achyutha anantha govinda
om sri achyutha anantha govinda
om sri achyutha anantha govinda
om sri achyutha anantha govinda
om sri achyutha anantha govinda
om sri achyutha anantha govinda
om sri achyutha anantha govinda
om sri achyutha anantha govinda
om sri achyutha anantha govinda
om sri achyutha anantha govinda
om sri achyutha anantha govinda
om sri achyutha anantha govinda
om sri achyutha anantha govinda
om sri achyutha anantha govinda
om sri achyutha anantha govinda
om sri achyutha anantha govinda
om sri achyutha anantha govinda
om sri achyutha anantha govinda

om namashivay
